# Form implementation generated from reading ui file 'picard-plugin-keep-only-tags/options_keep_only_tags.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_KeepOnlyTagsOptionsPage(object):
    def setupUi(self, KeepOnlyTagsOptionsPage):
        KeepOnlyTagsOptionsPage.setObjectName("KeepOnlyTagsOptionsPage")
        KeepOnlyTagsOptionsPage.resize(561, 523)
        KeepOnlyTagsOptionsPage.setMinimumSize(QtCore.QSize(0, 0))
        KeepOnlyTagsOptionsPage.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.verticalLayout = QtWidgets.QVBoxLayout(KeepOnlyTagsOptionsPage)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.page_title = QtWidgets.QLabel(parent=KeepOnlyTagsOptionsPage)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.page_title.setFont(font)
        self.page_title.setObjectName("page_title")
        self.verticalLayout.addWidget(self.page_title)
        self.page_text = QtWidgets.QLabel(parent=KeepOnlyTagsOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_text.sizePolicy().hasHeightForWidth())
        self.page_text.setSizePolicy(sizePolicy)
        self.page_text.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.page_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading | QtCore.Qt.AlignmentFlag.AlignLeft | QtCore.Qt.AlignmentFlag.AlignTop)
        self.page_text.setWordWrap(True)
        self.page_text.setObjectName("page_text")
        self.verticalLayout.addWidget(self.page_text)
        spacerItem = QtWidgets.QSpacerItem(20, 6, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.tags_list_title = QtWidgets.QLabel(parent=KeepOnlyTagsOptionsPage)
        font = QtGui.QFont()
        font.setBold(True)
        self.tags_list_title.setFont(font)
        self.tags_list_title.setObjectName("tags_list_title")
        self.verticalLayout.addWidget(self.tags_list_title)
        self.tags_list_text = QtWidgets.QPlainTextEdit(parent=KeepOnlyTagsOptionsPage)
        self.tags_list_text.setPlainText("")
        self.tags_list_text.setObjectName("tags_list_text")
        self.verticalLayout.addWidget(self.tags_list_text)

        self.retranslateUi(KeepOnlyTagsOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(KeepOnlyTagsOptionsPage)

    def retranslateUi(self, KeepOnlyTagsOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        KeepOnlyTagsOptionsPage.setWindowTitle(_translate("KeepOnlyTagsOptionsPage", "form.title"))
        self.page_title.setText(_translate("KeepOnlyTagsOptionsPage", "page.title"))
        self.page_text.setText(_translate("KeepOnlyTagsOptionsPage", "page.text"))
        self.tags_list_title.setText(_translate("KeepOnlyTagsOptionsPage", "section.tags_list.title"))
        self.tags_list_text.setPlaceholderText(_translate("KeepOnlyTagsOptionsPage", "section.tags_list.placeholder"))
